version: '3.9'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: test-task-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadminpass
    image: mongo
    volumes:
      - ../sampleDB:/data/db
      - ./sampleDB:/home